#dice que contenedores existen
#como se conectan
#que puertos usan
#que volumenes comparten

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./srcs/requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build:
      context: ./srcs/requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: unless-stopped

  nginx:
    container_name: nginx
    build:
      context: ./srcs/requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: unless-stopped

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/nmagro-r/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/nmagro-r/data/mariadb

networks:
  inception:
    driver: bridge